version: '3'

services:
  migration:
    container_name: migration
    image: ${ECR_REPOSITORY_MIGRATION}
    build:
      context: .
      dockerfile: ./infra/docker/go/migration/Dockerfile
      target: image
      args:
        ENVIRONMENT: ${ENVIRONMENT}
        POSTGRES_URL: ${POSTGRES_URL}
        POSTGRES_MAX_CONNECTIONS: ${POSTGRES_MAX_CONNECTIONS}
        POSTGRES_MAX_IDLE_CONNECTIONS: ${POSTGRES_MAX_IDLE_CONNECTIONS}
    tty: true
    volumes:
      - .:/enva/migration
