version: '3'

services:
  api:
    container_name: api
    image: ${ECR_REPOSITORY_API}
    build:
      context: .
      dockerfile: ./infra/docker/go/image/Dockerfile
    tty: true
    volumes:
      - .:/enva
