version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    ports:
      - 8001:80
    environment:
      LOCAL_HOST: "nginx"
