version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    ports:
      - 8001:80
    environment:
      - LOCAL_HOST: dummy
  api:
    container_name: enva-api
    env_file: # @TODO delete and to github
      - .env.prod
    build:
      context: .
      dockerfile: ./infra/docker/go/Dockerfile
      target: prod
    tty: true
    volumes:
      - .:/enva
    depends_on:
      - postgres
