version: '3'
services:
  postgres:
    container_name: enva-postgres
    image: postgres:13.3
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./infra/docker/postgres:/docker-entrypoint-initdb.d
      - ./tmp/postgresql-data:/var/lib/postgres/data:z
