version: '3'

services:
  api:
    container_name: enva-api-dev
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./infra/docker/go/Dockerfile
      target: ${ENV}
    tty: true
    stdin_open: true
    volumes:
      - .:/enva
