version: '3'

services:
  api:
    container_name: api
    image: ${ECR_REPOSITORY_API}
    build:
      context: .
      dockerfile: ./infra/docker/go/image/Dockerfile
      target: image
      args:
        ENVIRONMENT: ${ENVIRONMENT}
        API_PROTOCOL: ${API_PROTOCOL}
        API_HOST: ${API_HOST}
        API_PORT: ${API_PORT}
        FRONT_PROTOCOL: ${FRONT_PROTOCOL}
        FRONT_HOST: ${FRONT_HOST}
        FRONT_PORT: ${FRONT_PORT}
        POSTGRES_URL: ${POSTGRES_URL}
        POSTGRES_MAX_CONNECTIONS: ${POSTGRES_MAX_CONNECTIONS}
        POSTGRES_MAX_IDLE_CONNECTIONS: ${POSTGRES_MAX_IDLE_CONNECTIONS}
        COGNITO_REGION: ${COGNITO_REGION}
        COGNITO_USERPOOL_ID: ${COGNITO_USERPOOL_ID}
        COGNITO_SECRET: ${COGNITO_SECRET}
        CLI_API_URL: ${CLI_API_URL}
        EMAIL_HOST: ${EMAIL_HOST}
        EMAIL_HOST_USER: ${EMAIL_HOST_USER}
        EMAIL_HOST_PASS: ${EMAIL_HOST_PASS}
        EMAIL_PORT: ${EMAIL_PORT}
        SENTRY_DSN: ${SENTRY_DSN}
    tty: true
    volumes:
      - .:/enva
