version: '3'

services:
  nginx:
    container_name: nginx
    image: ${ECR_REPOSITORY_NGINX}
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    ports:
      - 80:80
    environment:
      LOCAL_HOST: "127.0.0.1"
