BEGIN;

DROP TABLE IF EXISTS rel_org_members;
DROP TABLE IF EXISTS org_invitations;
DROP TABLE IF EXISTS kvs;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS orgs;
DROP TABLE IF EXISTS ssh_keys;
DROP TABLE IF EXISTS users;

DROP EXTENSION IF EXISTS pgcrypto;

COMMIT;
