name: BIN
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - "enva/commands/version.json"
jobs:
  enva:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go
      - name: checkout
        uses: actions/checkout@v2
      - name: touch tar
        run: make touch/tar
      - name: build binary and compress
        run: make build/cli && make compress
        env:
          CLI_API_URL: http://localhost:8000
      - name: create pull request
        if: success()
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          base: master
          branch: compiled_cli_binary
          delete-branch: true
          commit-message: new cli tar.gz
          title: update cli bin file
          body: |
            cli bin new

            Auto pushed by bot
