name: CD
on:
  push:
    branches:
      - master
env:
  AWS_REGION: ap-northeast-1
  ENV: ${{ secrets.ENV }}
  # api info
  API_PROTCOL: ${{ secrets.API_PROTCOL }}
  API_HOST: ${{ secrets.API_PROTCOL }}
  API_PORT:
  # front info
  FRONT_PROTOCOL: ${{ secrets.FRONT_PROTOCOL }}
  FRONT_PORT:
  # db
  POSTGRES_URL: ${{ secrets.POSTGRES_URL}}
  POSTGRES_MAX_CONNECTIONS: ${{ secrets.POSTGRES_MAX_CONNECTIONS }}
  POSTGRES_MAX_IDLE_CONNECTIONS: ${{ secrets.POSTGRES_MAX_IDLE_CONNECTIONS }}
  # cognito
  COGNITO_REGION: ${{ secrets.COGNITO_REGION }}
  COGNITO_USERPOOL_ID: ${{ secrets.COGNITO_USERPOOL_ID }}
  COGNITO_SECRET: ${{ secrets.COGNITO_SECRET }}
  # cli
  CLI_API_URL: ${{ secrets.CLI_API_URL }}
  # email
  EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
  EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
  EMAIL_HOST_PASS: ${{ secrets.EMAIL_HOST_PASS }}
  EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
  # sentry
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  # ecr
  ECR_REGISTRY_API: ${{ secrets.ECR_REGISTRY_API }}
  ECR_REPOSITORY_API: ${{ secrets.ECR_REPOSITORY_API }}
  ECR_REGISTRY_NGINX: ${{ secrets.ECR_REGISTRY_NGINX }}
  ECR_REPOSITORY_NGINX: ${{ secrets.ECR_REPOSITORY_NGINX }}
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go
      - name: checkout
        uses: actions/checkout@v2
      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
  ecr:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.3.3
      # - name: build-api
      #   run: make container/build
      - name: image and push
        id: image-and-push
        run: |
          make container/image
          make container/push
